# Minimum version of fastlane
fastlane_version "1.32.1"

default_platform :ios

platform :ios do

before_all do
ENV['DEVELOPER_DIR'] = '/Applications/Xcode-Beta.app/Contents/Developer'
end

lane :build do
gym
end

error do |lane, exception|
# This block is called, if there was an error running a specific lane.
end

end
